== 11970 Message Controller Generation

=== 1 Abstract

When connecting an xtUML-generated application to a browser-based client it is often necessary to produce message controller functionality that serves as an intermediary between the xtUML server application and the communication mechanism to the client(s). A method must be supplied for each port activity of a marked interface. These methods handle serialization of messaging to the client and deserialization of messaging from the client to the xtUML application. 

This topic, <<dr-1>>, now subsumes <<dr-2>>. 

=== 2 Introduction and Background

Some web frameworks, such as Spring, require message controller functionality to handle message traffic flowing between a server application and its clients.   Manually writing such code is tedious and error-prone, so this feature automates the process.

Refer to the hand-coded message controller classes within the 
https://github.com/johnrwolfe/CarPark/tree/master/Deployment/src/main/java/deployment[CarPark Deployment project] 
for early examples.

The CarPark example also employs a _shell component_ to represent each type of client.  This idiom minimizes the number of generated files that must be manually modified and maintained when connecting a generated application to a client without modifying the model compiler.  However, the shell component adds no value and can be eliminated once the model compiler is capable of generating message controllers. Furthermore, model compiler access allows the functionality of the messsage controller to be included by modifying the code generated for the port.

=== 3 Requirements

. A mark specifies that an application makes use of Spring servlet capability.
. A mark specifies for which ports message controller functionality should be generated.
. WebSocket communication within the Spring framework is supported.

=== 4 Analysis

Currently, only WebSocket communication within the Spring framework is supported.

Note that this implementation requires that WebSocket port names be unique within a deployment.
This implementation also limits a deployment to containining a single application.

Marking is applied on a port boundary, and the message controller functionality is generated as a modification to the generated port class for the marked port.


=== 5 Design

Message controller functionality must provide for handling messages outgoing from the application and inbound to the application.

Inbound messages present as instances of message-specific classes; member data is unpacked and passes as parameter data to port activities.

Outbound messages are serialized and delivered to clients as the payload member of a generic Spring message class.

The constructors for the application itself and any marked ports are invoked as part of Spring initialization; this must be accounted for. The constructors are modified to save their instance value in a `singleton` attribute, from which the instance can be retrieved as needed. 

The Spring framework requires that an inbound message handling method be prefixed with a '@MessageMapping (/xxxx)" annotation where xxx names the message to be handled by the method. The handler method invokes the corresponding port activity in the application, extracting parameters from the received message instance. 

Messages originating from an application port activity invoke an outbound handler method which creates an instance of the appropriate message and invokes Spring's "convertAndSend" adding a destination identifier. The destination identifier is of the form "/topic/xxx/yyy"; a client can subscribe to topic xxx, perhaps refined by yyy to identify a particular client instance.  A marking on a port boundary can establish the topic value; a related mark can specify the name of a message parameter which, if present, supplies a message-specific topic refinement value.


=== 6 Work required

. Add a mark named `ApplicationNature` to be applied to the application; a value "SpringApplication" is supported.
. Add a mark named `PortType` to be applied to a port; a value "SpringWebSocket" is supported
. Develop template(s) for rendering WebSocket configuration and application initialization modification.
. Develop template(s) to unpack parameters from inbound messages, directly invokng port activities.
. Modify port templates as necessary to directly send serialized outbound messages.
. Add marks to specify web socket endpoints; subscription topics, and topic refinement.

=== 7 Implementation Comments

. The marks named above are implemented along with `EndPoint`, `SubscriptionTopic` and `SubTopicParameter`.
. The Application class is subtyped to allow for specialized rendering of imports and initialization.
. Port class uses a subtyped PortDescriptor class for specialized rendering of imports and message handling.
. Application and Port constructors are modified to account for invocation from Spring.
. Port accessors render differently: Spring applications return a Port instance rather than creating it.
. A generic `SpringMsgClass` is generated: its members are `messageName` and the serialized `payload` string.
. The key `payload` retrieves a string in JSON format from which values are retrieved by parameter-name-as-key.
. The Port send method is overridden to serialize messages; a `null` test overrides the `satisfied()` test.
. Interfaces are rendered differently for WebSocket ports; the incoming messages carry message classes.
. Multiple architectural interfaces can now be transformed from a metamodel definition.
. A specialized (e.g. WebSocket) interface file is suffixed ("_sws") to differentiate it for marked port import.
. A marking associates an 'endpoint' socket name with a port; this name is used to open a client connection.


=== 8 Acceptance Test

An existing application has been built with developed markings and tested with browser clients.

=== 9 User Documentation

see: https://github.com/MaileTechnical/ciera/wiki/Marking

=== 10 Code Changes

https://github.com/amullarney/ciera/tree/Ciera11970_msgCtrl


=== 11 Document References

In this section, list all the documents that the reader may need to refer to.
Give the full path to reference a file.

. [[dr-1]] https://support.onefact.net/issues/11970
. [[dr-2]] https://support.onefact.net/issues/11971


