== 11970 Message Controller Generation

=== 1 Abstract

When connecting an xtUML-generated application to a browser-based client it is often necessary to produce
message-controller functionality that serves as an intermediary between the xtUML server application and 
the communication mechanism to the client(s). 

Along with serialization and deserialization of message data, a message controller provides a mechanism
for delivering inbound messages from a client to the xtUML application.

This topic, <<dr-1>>, now subsumes <<dr-2>>. 

=== 2 Introduction and Background

Some web frameworks, such as Spring, require message controller functionality to handle message 
traffic flowing between a server application and its clients.   Manually writing such code is 
tedious and error-prone, so this feature automates the process.

Refer to the hand-coded message controller classes within the 
https://github.com/johnrwolfe/CarPark/tree/master/Deployment/src/main/java/deployment[CarPark Deployment project] 
for early examples.

The CarPark example also employs a _shell component_ to represent each type of client.  This idiom minimizes the 
number of generated files that must be manually modified and maintained when connecting a generated application 
to a client without modifying the model compiler.  However, the shell component adds no value and can be 
eliminated once the model compiler is capable of generating message controllers.

=== 3 Requirements

Generate message-controller functionality similar to that illustrated in the hand-coded examples shown
in the CarPark system.
. Receive incoming messages from a client and deliver them to the xtUML application
. Transmit outgoing messages from the xtUML application to a client
. Serialize and deserialize message data as necessary

=== 4 Analysis

==== 4.1 Marking

Several marks are used to direct the generation of message-controller capabilities.

. Specify that the xtUML application leverages the Spring framework
. Indicate that a specific port must support WebSocket communications
. Specify the message-broker topic associated with a port
. Specify the name of a message parameter containing a topic-refinement value

==== 4.2 Limitations

. Currently, only WebSocket communication within the Spring framework is supported
. Each port marked as a WebSocket port must have a name that is unique within the application
. Each deployment may contain only a single xtUML application

=== 5 Design

Message controller functionality must provide for handling messages outgoing from the application 
and inbound to the application.

Inbound messages present as instances of message-specific generated classes; member data is 
unpacked and passed as parameter data to port activities.

Outbound messages are serialized and delivered to clients as the payload member of a generic Spring message class.

Rather than generate separate message-controller classes, as illustrated in the hand-coded examples in the CarPark
system, this solution integrates message-controller capabilities into the generated port class.

The constructors for the application itself, components, and any marked ports are invoked as part of Spring 
initialization; this must be accounted for. The constructors are modified to save their instance value in 
a `singleton` attribute, from which the instance can be retrieved as needed.

A method to handle each incoming message is generated and annoated with '@MessageMapping (/xxxx)" 
where xxx names the message to be handled by the method. The handler method invokes the corresponding 
port activity in the application, extracting parameters from the received message instance and passing
them along to the port-activity method.

For each outbound message from the application, a method is generated which creates and populates
an instance of the appropriate message class and then sends it to the destination.  The destination 
identifier is of the form "/topic/xxx/yyy"; a client can subscribe to topic xxx, perhaps refined by yyy to 
identify a particular client instance.  A marking on a port boundary can establish the topic value; a related 
mark can specify the name of a message parameter which, if present, supplies a message-specific topic refinement value.

As more than one port may formalize to an interface, and ports may be marked differently, the architecture 
now supports multiple Java interfaces transformed from the same modeled interface definition. Generated 
interface files may use a suffix for differentiation.

A configuration file required for WebSocket communication is also generated. 

=== 6 Work required

. Add a mark named `ApplicationNature` to be applied to the application; a value "SpringApplication" is supported.
. Add a mark named `PortType` to be applied to a port; a value "SpringWebSocket" is supported.
. Subtype Application, and an added PortDecriptor class, to capture transform specializations.
. Modify the multiplicity of the transformed architectural interface to allow different renderings.
. Develop template(s) for rendering WebSocket configuration and application initialization modification.
. Develop template(s) to unpack parameters from inbound messages, directly invokng port activities.
. Modify port templates as necessary to directly send serialized outbound messages.
. Add marks to specify web socket endpoints; subscription topics, and topic refinement.

=== 7 Implementation Comments

. The marks named above are implemented along with `EndPoint`, `SubscriptionTopic` and `SubTopicParameter`.
. The Application class is subtyped to allow for specialized rendering of imports and initialization.
. Port class uses a subtyped PortDescriptor class for specialized rendering of imports and message handling.
. Application and Port constructors are modified to account for direct invocation from Spring.
. Marked Port constructors use their Component's `Singleton()` to retrieve a context for supertype creation.
. Component Port accessors render differently: Spring applications return a Port instance rather than creating it.
. A generic `SpringMsgClass` is generated: its members are `messageName` and the serialized `payload` string.
. The message key `payload` retrieves a JSON string from which values are retrieved by parameter-name-as-key.
. The Port send method is overridden to serialize messages; a `null` test overrides the `satisfied()` test.
. Interfaces are rendered differently for WebSocket ports; the incoming messages carry message-specific instances.
. Multiple architectural interfaces can now be transformed from a modeled interface definition.
. A specialized (e.g. WebSocket) interface file is suffixed ("_sws") to differentiate it for marked port import.
. A marking associates an 'endpoint' socket name with a port; this name is used to open a client connection.
. A marking specifies a subscription topic associated with messages outgoing from a port.
. A marking specifies the name of an optional message parameter whose value, if present, will be appended to the topic.
. In several render operations, fragment rendering adds imports; `getFormattedImports()` moves to the end.


=== 8 Acceptance Test

An existing application has been built with developed markings and tested with browser clients.

=== 9 User Documentation

see: https://github.com/MaileTechnical/ciera/wiki/Marking

=== 10 Code Changes

https://github.com/amullarney/PilotPayroll/tree/11970_SpringWebSocket

=== 11 Document References

. [[dr-1]] https://support.onefact.net/issues/11970
. [[dr-2]] https://support.onefact.net/issues/11971


